#!/usr/bin/env bash

set -eufx -o pipefail

cd /mnt/etc/nixos
rm configuration.nix
curl -o configuration.nix https://raw.githubusercontent.com/usami/nixos-setup/master/configuration.nix

nixos-install --no-root-passwd
reboot
