#!/usr/bin/env bash

DEVICE=$1

set -euo pipefail

parted $DEVICE -- mklabel gpt
parted $DEVICE -- mkpart ESP fat32 1MiB 512MiB
parted $DEVICE -- mkpart primary 512MiB -8GiB
parted $DEVICE -- mkpart primary linux-swap -8GiB 100%
parted $DEVICE -- set 1 boot on
