#!/usr/bin/env bash

nix-env -i jq

DEVICE=/dev/$(lsblk -J | jq -r '.blockdevices[0].name')

echo "Fetch install scripts"
wget https://raw.githubusercontent.com/usami/nixos-setup/master/partition
wget https://raw.githubusercontent.com/usami/nixos-setup/master/setup

chmod +x partition
chmod +x setup

./partition $(DEVICE)
./setup $(DEVICE)p1 $(DEVICE)p2 $(DEVICE)p3

cd /mnt/etc/nixos
rm configuration.nix
wget https://raw.githubusercontent.com/usami/nixos-setup/master/configuration.nix

echo "Remove filesystem entries in hardware.nix"
sleep 5

vi hardware.nix

nixos-install
reboot
