#!/usr/bin/env bash

set -euo pipefail

nix-env -i jq

DEVICE=/dev/$(lsblk -J | jq -r '.blockdevices[] | .name' | grep nvme)
BRANCH=clean

echo "Fetch install scripts"
curl -o partition https://raw.githubusercontent.com/usami/nixos-setup/$BRANCH/partition
curl -o setup https://raw.githubusercontent.com/usami/nixos-setup/$BRANCH/setup

chmod +x partition
chmod +x setup

./partition $DEVICE 38
./setup "$DEVICE"p3 "$DEVICE"p1 "$DEVICE"p2

cd /mnt/etc/nixos
rm configuration.nix
curl -o configuration.nix https://raw.githubusercontent.com/usami/nixos-setup/$BRANCH/configuration.nix

vim hardware-configuration.nix

nixos-install --no-root-passwd

umount /mnt/{boot,}
swapoff /dev/disk/by-label/swap
cryptsetup luksClose crypted

reboot
